doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        # For unknown reasons, adding schema_filter actually does the opposite and will not ignore the table. 
        #schema_filter: ~^(?!t_)~

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            acl_permission:  App\Doctrine\Types\AclPermissionType
            # requiredRole:  App\Doctrine\Types\RequiredRoleType
            currency:  App\Doctrine\Types\CurrencyType
            #money:  App\Doctrine\Types\MoneyType
            #money:  Tbbc\MoneyBundle\Type\MoneyType
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
        # How should mapping_types be used?
        #mapping_types:
            #???
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Money:
                type: xml
                dir: '%kernel.project_dir%/src/Resources/config/doctrine'
                prefix: Money
        filters:
            tenant_filter: App\Doctrine\Filters\TenantFilter
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        resolve_target_entities:
            App\Entity\User\UserInterface: App\Entity\User\AbstractUser
            App\Entity\Organization\OrganizationInterface: App\Entity\Organization\AbstractOrganization
            App\Entity\Organization\TenantInterface: App\Entity\Organization\Tenant
            App\Entity\Organization\VendorInterface: App\Entity\Organization\Vendor
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
